version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DB_TYPE=sqlite
      - DB_PATH=/app/data/urlshortener.db
      - BASE_URL=http://localhost:8081
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    networks:
      - urlshortener_network

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - urlshortener_network

volumes:
  redis_data:

networks:
  urlshortener_network:
    driver: bridge 