services:
  - type: web
    name: url-shortener
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: REDIS_HOST
        value: url-shortener-redis.internal
      - key: REDIS_PORT
        value: "6379"
      - key: BASE_URL
        value: https://url-shortener.onrender.com
    disk:
      name: sqlite-data
      mountPath: /app/data
      sizeGB: 1

  - type: redis
    name: url-shortener-redis
    plan: free
    ipAllowList: [] 