services:
  - type: web
    name: url-shortener
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BASE_URL
        value: https://url-shortener.onrender.com
      - key: REDIS_URL
        value: redis://localhost:6379/0
    disk:
      name: sqlite-data
      mountPath: /app/data
      sizeGB: 1
    healthCheckPath: /health
    autoDeploy: true

  - type: redis
    name: url-shortener-redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: noeviction 