CREATE TABLE IF NOT EXISTS urls (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    long_url TEXT NOT NULL,
    short_id VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clicks (
    id SERIAL PRIMARY KEY,
    url_id INTEGER NOT NULL REFERENCES urls(id),
    ip_address VARCHAR(45) NOT NULL,
    user_agent TEXT NOT NULL,
    country VARCHAR(2) NOT NULL,
    device VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
); 