ALTER TABLE clicks
ADD COLUMN city VARCHAR(255),
ADD COLUMN latitude DOUBLE PRECISION,
ADD COLUMN longitude DOUBLE PRECISION,
ADD COLUMN timezone VARCHAR(100),
ADD COLUMN country_code VARCHAR(2); 